
import "../../public/styles/reset.css";
import "../../public/styles/variable.css";
import "./globals.css";
import Providers from "./providers";

import Nav from './components/Nav';
import Modal from './components/Modal';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className='wrapper'>
          <Nav />
          
          <Modal />
          {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
